name = "military-training-sun-vote"
compatibility_date = "2026-08-18"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "military-training-sun-vote"
database_id = "ed295248-86bb-46e5-b763-d8ad5e031ae6"
